- name: update all apt packages
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
  when: base_os == "ubuntu14"
- name: update all yum packages
  yum:
    name: "*"
    state: latest
  when: base_os == "cent7"
